### ISSUE TITLE
Create a shortened URL for the workshop front page

### ISSUE THREAD

**Issue by embray** [abostroem/2015-01-03-aas#1]
Currently attendees will have to go to: http://abostroem.github.io/2015-01-03-aas/ to get to the workshop front page with the schedule and installation instructions.  I've usually found some people have a hard time with the github URLs (what the heck is a github?) and spelling people's usernames (especially when I was using "iguananaut" more often).

I usually use bit.ly to make shortened URLs.  I was just wondering if we had any thoughts as to what to name it.  Maybe bit.ly/swcarpentry-aas-225?

**Comment by embray** [comment]
(This also goes back to the comment I've made a few times in meetings that we need our own 'swc' URL shortening service :D)

**Comment by jiffyclub** [comment]
In the spirit of shortness, maybe bit.ly/swc-aas-225?

**Comment by embray** [comment]
:+1: to swc-aas-225

**Comment by abostroem** [comment]
Done
bit.ly/swc-aas-225
